### ISSUE TITLE
Create Item in an empty pane crashes the application

### ISSUE THREAD

**Issue by henwik-1** [SamuelHakansson/doorstop-qt#1]
If there are no documents in the documents pane, the Create Item operation crashes the application.

(doorstop-qt v1.0)

![Doorstop_CreateItemCrash](https://user-images.githubusercontent.com/48443755/63838265-52472500-c97d-11e9-8cd4-569640fd2737.png)

**Comment by SamuelHakansson** [comment]
Fixed.
