### ISSUE TITLE
Create sibling item not available

### ISSUE THREAD

**Issue by henwik-1** [SamuelHakansson/doorstop-qt#2]
It seems like it's only possible to create child items in the document pane (at the far left).

(doorstop-qt v1.0)

![Doorstop_CreateSiblingItemNotAvailable](https://user-images.githubusercontent.com/48443755/63838782-47d95b00-c97e-11e9-8c31-f135ed8f4598.png)

**Comment by SamuelHakansson** [comment]
Fixed. Now possible to creating siblings in the document view.
