### ISSUE TITLE
Create child item not available unless Heading specified

### ISSUE THREAD

**Issue by henwik-1** [SamuelHakansson/doorstop-qt#3]
The only way to have access to Create Child Item in the pane with Requirements/Tests/Products seems to be to specify it as a Heading. Is this implicit in Doorstop or can we allow for also a heading-less item to have children?

(doorstop-qt v1.0)

![Doorstop_CreateChildItemNotAvailable](https://user-images.githubusercontent.com/48443755/63838814-5cb5ee80-c97e-11e9-97fe-549539e982fa.png)

**Comment by SamuelHakansson** [comment]
Was not built into Doorstop. Fixed.
