### ISSUE TITLE
Document names changed when related items is created

### ISSUE THREAD

**Issue by henwik-1** [SamuelHakansson/doorstop-qt#5]
A document name including white spaces can be created but as soon as an item is created related to this, the name removes everything after the first white space. If this is inherent from Doorstop, please remove the possibility of using white spaces in the names.

(doorstop-qt v1.0)

![Doorstop_DocumentNamesChanged](https://user-images.githubusercontent.com/48443755/63840788-ea470d80-c981-11e9-82d0-ee177915fcb1.png)

**Comment by SamuelHakansson** [comment]
Forgot to look at space as an illegal character. Fixed.

**Comment by henwik-1** [comment]
Works fine now.
