### ISSUE TITLE
Use "Title" as item describer instead of Feature Name

### ISSUE THREAD

**Issue by henwik-1** [SamuelHakansson/doorstop-qt#6]
Currently "Feature name" is used as a friendly description of an item. Please use another tag, e.g. "Title" instead as this is much more general and can be used for all three variants: Tests, Products, Requirements.

**Comment by SamuelHakansson** [comment]
Fixed. It now uses regex to check for the first occurence of a bold text (**bold text**) and stops when it finds \n to find the title of the item.
