### ISSUE TITLE
A product sibling can crash the application

### ISSUE THREAD

**Issue by henwik-1** [SamuelHakansson/doorstop-qt#7]
After creating a sibling product called "123", any interaction with this crashes the application. After a few restart attempts/crashes, I got the fatal error below.

Scenario:
1. Create a product document where the name has white spaces
2. Create an item for this document
  -> The product document name removes everything after the first whitespace
3. Create a child document
4. Try to create an item for the child document created in 3.
  -> ERROR: The application crashes
5. Restart application
6. Try to remove the document created in 1
  -> ERROR: The application crashes and a restart creates the fatal error below

Workaround: Remove the entries in the Products file structure.

(doorstop-qt v1.0)

![Doorstop_FatalError](https://user-images.githubusercontent.com/48443755/63841781-b79e1480-c983-11e9-986d-84c25b8642c8.png)

**Comment by SamuelHakansson** [comment]
This should be fixed as spaces are no longer allowed.

**Comment by henwik-1** [comment]
Works fine now.
